"""Generate .github/workflows/book.yml from classes.yml.

Booking opens 167h before a class = same weekday, (start time + 1 hour). We fire
each job at several FIRE_LEAD_MINS minutes before that. GitHub cron is best-effort
and silently drops/delays triggers under load, so we emit a redundant trigger at
each lead — if one is skipped, another still fires before the open, waits for the
true instant, and books. GitHub cron is also fixed UTC and ignores Pacific DST, so
each lead emits two cron lines (PDT = UTC-7, PST = UTC-8); the script computes the
true open instant and waits, and any redundant run no-ops via the OPEN_GUARD (the
booking API is idempotent, so a duplicate just sees "already booked"). Run:
  python scripts/gen_workflow.py
"""

from __future__ import annotations

import os
from datetime import datetime, timedelta

import yaml

# Fire a trigger at each of these minutes before booking opens. Multiple leads give
# redundancy against GitHub dropping a scheduled trigger; all fire before the open
# so whichever runs waits for the precise instant and books on the first attempt.
FIRE_LEAD_MINS = [25, 15]
CRON_DOW = {"Mon": 1, "Tue": 2, "Wed": 3, "Thu": 4, "Fri": 5, "Sat": 6, "Sun": 0}
HERE = os.path.dirname(__file__)
CONFIG = os.path.join(HERE, os.pardir, "classes.yml")
OUT = os.path.join(HERE, os.pardir, ".github", "workflows", "book.yml")


def cron_lines(klass) -> list[tuple[str, str]]:
    """Return [(cron_expr, comment), ...] for a class — one per UTC offset."""
    dow = klass["weekday"]
    h, m = (int(x) for x in klass["start"].split(":"))
    out = []
    for lead in FIRE_LEAD_MINS:
        # open = start + 1h; fire = open - lead, as a same-day local time.
        fire = datetime(2000, 1, 3, h, m) + timedelta(hours=1) - timedelta(minutes=lead)
        for off, season in ((7, "PDT"), (8, "PST")):
            ut = fire + timedelta(hours=off)            # local -> UTC
            # day-of-week only shifts if the +offset crosses midnight; our fire times
            # are late morning/midday Pacific so UTC stays the same calendar weekday.
            assert ut.day == fire.day, "offset crossed midnight; handle DOW shift"
            out.append((f"{ut.minute} {ut.hour} * * {CRON_DOW[dow]}",
                        f"{klass['key']} — opens {dow} {h+1:02d}:{m:02d} PT "
                        f"({season}, fire -{lead}m)"))
    return out


def main():
    cfg = yaml.safe_load(open(CONFIG))
    crons = []
    for k in cfg["classes"]:
        crons.extend(cron_lines(k))

    sched = "\n".join(f"    - cron: \"{expr}\"  # {c}" for expr, c in crons)
    keys = [k["key"] for k in cfg["classes"]]
    body = f"""# AUTO-GENERATED by scripts/gen_workflow.py — edit classes.yml then regenerate.
name: Book YMCA classes

on:
  schedule:
{sched}
  workflow_dispatch:
    inputs:
      class_key:
        description: "Class key to book now (see classes.yml). Blank = decide from schedule."
        required: false
        default: ""

concurrency:
  group: book-${{{{ github.run_id }}}}

jobs:
  book:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install -r requirements.txt
      - run: python -m playwright install --with-deps chromium
      - name: Book
        env:
          EGYM_USERNAME: ${{{{ secrets.EGYM_USERNAME }}}}
          EGYM_PASSWORD: ${{{{ secrets.EGYM_PASSWORD }}}}
        run: |
          if [ -n "${{{{ github.event.inputs.class_key }}}}" ]; then
            python -m src.main --class "${{{{ github.event.inputs.class_key }}}}"
          else
            python scripts/run_due.py
          fi
"""
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write(body)
    print(f"Wrote {OUT} with {len(crons)} cron lines for {len(keys)} classes.")


if __name__ == "__main__":
    main()
